name: scrcpy-mediamtx-docker

services:
  scrcpy:
    image: tommytz/scrcpy-docker:latest
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      # preserve authorization keys
      - scrcpy_adb_keys:/root/.android
    environment:
      ADB_VENDOR_KEYS: /root/.android
    privileged: true
    network_mode: host
    tty: true
    stdin_open: true
    restart: unless-stopped

  mediamtx:
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - MTX_PROTOCOLS=tcp,udp
      - MTX_WEBRTCADDITIONALHOSTS=127.0.0.1,192.168.0.224
    image: bluenviron/mediamtx:latest-ffmpeg
    volumes: 
      - $PWD/mediamtx.yml:/mediamtx.yml
    restart: unless-stopped


volumes:
  scrcpy_adb_keys:
